### ISSUE TITLE
URxvt plugin

### ISSUE THREAD

**Issue by tux1c** [mkamensky/Text-Bidi#2]
Hello,

I've started using your library, along with the URxvt plugin on my system (Gentoo Linux), and I have stumbled upon some issues:
1. The latest commit breaks the plugin. Tested both on Gentoo and Arch Linux on latest versions of urxvt. The moment that you type a hebrew character, the terminal emulator locks. Previous commit works flawlessly.
Now, those issues might be fixed in the new commit, but I can not test :) : 
2. Scrollback text is not inverted, and is broken as if not running the plugin (i.e. שלום turns to םולש)
3. The plugin is causing CRAZY memory leaking. Now, I tested it in some primitive way, but I've concluded it's the plugin to blame; I first ran urxvt with the plugin loaded, and started spamming hebrew characters. Memory usage went up in 100mb over less than 30 seconds of spamming (around 100 mesages, say?), then, I killed urxvt and launched it without the plugin, did the same thing for same amount of time, yet the RAM usage stayed around the same numbers. I noticed that leak when, after a day of chatting in an IRC channel, I saw that my urxvt would use _2 GIB OF RAM_.

it would be wonderful if you were to fix, or, guide me on fixing (even general directions to where to look at, how to debug, etc), as I find this plugin VERY useful :)

---

שלום,

אני משתמש בספרייה שלך, ובפלאגין שכתבת למסוף על המערכת שלי (ג׳נטו לינוקס), ונתקלתי בכמה בעיות:
1. העדכון האחרון שלך לפלאגין שובר אותו לגמרי והאמולטור נתקע ברגע שהוא מקבל תו בעברית, בדקתי זאת על כמה מערכות (ג׳נטו וארצ׳ לינוקס) בגרסא האחרונה של urxvt.
כמובן שהגרסא האחת לפני האחרונה עובדת.

עכשיו, יכול להיות והבעיות האלו נפתרו בעדכון האחרון, אך אני לא יכול לבדוק זאת:
2. כל הטקסט שנמצא בסקרולבאק של המסוף לא מתהפך, משמע, מילים כמו ׳שלום׳ בכל זאת מופיעות כ׳םולש׳.
3. הפלאגין גורם לדליפת זכרון חמורה.
הפעלתי את המסוף עם הפלאגין, והספמתי תווים רנדומאליים בעברית במשך כ30 שניות, והשימוש בראם של המסוף עלה לכ100mb.
לאחר מכן, הפעלתי את המסוף מחדש, ללא הפלאגין, ביצעתי תהליך זהה, והשימוש בראם כמעט ולא השתנה.
שמתי לב לדליפה לאחר ששוחחתי יום שלם בIRC
בשרת דובר עברית, וראיתי כי השימוש בראם עלה ל2 ג׳ב, דבר החורג מאוד מן הרגיל.

אשמח אם תתקן את אחת, או כל הבעיות האלו, או שלפחות תפנה אותי לכיוון הנכון לתיקון הבעיות ואשלח לך PR
הפלאגין מאוד נחוץ ושימושי לי :)

**Comment by mkamensky** [comment]
@Tux1c , thanks for the report. Just to verify, you are using the version currently on git, not the latest released version (2.09), right? I made some changes to deal better with paragraphs, but it is likely to contain problems, and I'm not sure right now why did I push it (I did use this version for a few months last year, though, and don't remember running into serious problems). Anyway, I will be happy to get some help testing it, but if you are just interested in using it, please use the version that comes with the 2.09 release.

(1) was a bug that I just fixed, that occurred when the new LRE resource was empty. The point of this resource (and the associated one, PDF) is to insert direction hints on certain characters (or strings). What I have in my resources file is
URxvt.bidi.LRE: \\\\[([]
URxvt.bidi.PDF: \\\\[)\\]]
but anyway, it should now also work when they are empty

(2) Seems to have always been there, I never noticed it (I use tmux, so don't use the scrollbar much), and I guess it happens because on_refresh_begin is not called when you scroll back. I will try to look into it

(3) is not very surprising, I had some issues with memory leaks in the past, though I didn't notice them recently (with the version that comes with 2.09). Again, I will try to look into it.

Thanks again for the report

**Comment by Tux1c** [comment]
Hey @mkamensky,

Yup, I was referring to the latest git commit. Will gladly test and debug with you, actually started looking into Perl to see how it works and how to get around with it.

I am currently away, but I will test the latest commit and report back as soon as I can. I will also look into URxvt documentation and Perl to see how I can help the most, whether it would be more accurate reports or maybe even sends some PRs or something.

Thank you for your time and attention :)

**Comment by AlexK-IL** [comment]
I hope it's the proper place to ask this, I wasn't sure if I should submit a new issue.
I have installed your [latest version on cpan](http://www.cpan.org/modules/by-module/Text/KAMENSKY/Text-Bidi-2.11.tar.gz).
Then I put your urxvt plugin which I found [here on the bottom of the mail](http://lists.schmorp.de/pipermail/rxvt-unicode/2006q3/000321.html) into `/usr/lib/urxvt/perl/bidi`.
Then I have added to my `.Xdefaults` file these lines:
```
URxvt.perl-ext: default,bidi
URxvt.bidi.enabled: 1
```
But then when I restart urxvt it reacts very strange, here's a [screenshot](https://s17.postimg.org/ndm5m56fj/2016_10_02_14_12_34_screenshot.png).
If it matters, I run archlinux with i3wm.

**Comment by Konfekt** [comment]
Hopefully my instructions given in the [wiki](https://github.com/mkamensky/Text-Bidi/wiki/Installation-Instructions) help to install a the most recent versions of all sources and programs needed to add bidi support to URxvt.

**Comment by mkamensky** [comment]
@Konfekt Great, thanks! I made some small edits
