### ISSUE TITLE
Disable line direction?

### ISSUE THREAD

**Issue by AlexK-IL** [mkamensky/Text-Bidi#5]
Hello mkamensky!
When using the urxvt plugin it confuses me that whenever a line starts with hebrew the whole line is moved to the right side, see [screenshot from vim](https://gyazo.com/1cffe26f98ed34d8ec9b47a7deb533d0) for example.
The content of `example.txt` from the screenshot above is:

```
test מתחיל באנגלית
מתחיל בעברית test
test starts in english
```

Also notice how there are two cursors, one on the letter `ל` in the second line and one on the left in the same line.
Can it be disabled so it will always be on the left side?

**Comment by mkamensky** [comment]
Hi,
The line starts on the right since, by default, the plugin considers each line to be a paragraph, and this "paragraph" is determined to be RTL (since it starts with an RTL char). This can be changed using the `par` resource which, if set to true, will make the term work with real paragraphs. By default, a paragraph starts with a blank line, but this can be changed using the `ParReset` and `ParResetAfter` resources (there is an example in the docs.) There is no option to hard-fix it on a particular direction.

Regarding the cursor, I couldn't find a way to remove the original cursor, I asked the urxvt maintainers and they refused to include an option to hide or move the original cursor. One thing that can be done is make them more visually distinct. I have `cursorUnderline` true for terms I use to edit Hebrew, and also the usual cursor in green, while the real (logical) cursor is really just reverse video.

**Comment by AlexK-IL** [comment]
Could you please direct me to the docs?
I couldn't do it both the things you suggested to me.

**Comment by mkamensky** [comment]
It's right at the top of the bidi plugin
